bibeltreue-gemeinden/bibeltreue_gemeinden/urls.py
"""
Definition of urls for bibeltreue_gemeinden.
"""

from datetime import datetime
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
import django.contrib.auth.views as auth_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

import app.views

# Uncomment the next lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

# Uncomment the next line to enable the admin:
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('favicon.ico'),
            permanent=False),
        name="favicon"
    ),
]
urlpatterns += i18n_patterns(
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^impressum', app.views.impressum, name='impressum'),
    url(r'^datenschutz', app.views.datenschutz, name='datenschutz'),
    url(r'^accounts/login/$',
        auth_views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
                {
                    'title': 'Log in',
                    'year': datetime.now().year,
                }
        },
        name='login'),
    url(r'^accounts/logout$',
        auth_views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^accounts/signup/$', app.views.signup, name='signup'),
    url(r'^ajax/osm_location/$', app.views.get_location_from_osm, name="osm_location"),
    url(r'^ajax/bounding_box/$', app.views.get_places_by_bounding_box, name="bounding_box"),
    url(r'^ajax/all_places/$', app.views.get_all_places, name="all_places"),
    url(r'^accounts/account_activation_sent/$', app.views.account_activation_sent, name='account_activation_sent'),
    url(r'^accounts/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        app.views.activate, name='activate'),
    url(r'^accounts/update_profile/$', app.views.update_profile, name="update_profile"),
    url(r'^accounts/password_reset/$', auth_views.password_reset,
        {
            'template_name': 'app/password_reset_form.html',
            'extra_context':
                {
                    'year': datetime.now().year,
                }
        },
        name='password_reset'),
    url(r'^accounts/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^places/$', app.views.all_places, name="places"),
    url(r'^places/add/$', app.views.add_place, name="add_place"),
    url(r'^places/(?P<id>[0-9]+)/$', app.views.edit_place, name="edit_place"),
    url(r'^places/batch/$', app.views.batch_add_places, name="batch_add"),
    url(r'^places/command/$', app.views.submit_command, name="command"),

    # url(r'^waypoints/', include('waypoints.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

bibeltreue-gemeinden/waypoints/urls.py
# Import django modules
from django.conf.urls import url
from waypoints import views


urlpatterns = [
    url(r'^$', views.index, name='waypoints-index'),
    url(r'^save$', views.save, name='waypoints-save'),
]

bibeltreue-gemeinden/app/models.py
"""
Definition of models.
"""

from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from app import custom_fields


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    email_confirmed = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    instance.profile.save()


class Bruderschaft(models.Model):
    name = models.CharField(max_length=250, blank=False, unique=True)
    description = models.TextField()

    def __unicode__(self):
        return u'{obj.name}'.format(obj=self)


class Domination(models.Model):
    name = models.CharField(max_length=250, blank=False, unique=True)
    description = models.TextField()

    def __unicode__(self):
        return u'{obj.name}'.format(obj=self)


class Contact(models.Model):
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone
    # number must be entered in the format: '+999999999'.  Up to 15 digits
    # allowed.")
    phone_number = models.CharField(max_length=15, blank=False)
    e_mail = models.EmailField(max_length=256, blank=True)
    website = models.URLField(max_length=500, blank=True)

    def __unicode__(self):
        return u'{obj.first_name} {obj.last_name} {obj.phone_number} {obj.e_mail} {obj.website}'.format(obj=self)


class Place(models.Model):
    name = models.CharField(max_length=250, blank=False)
    description = models.TextField(blank=True)

    street = models.CharField(max_length=120, blank=False)
    hous_number = models.CharField(max_length=10, blank=False)
    postcode = models.CharField(max_length=10, blank=False)
    city = models.CharField(max_length=250, blank=False)
    country = models.CharField(max_length=250, blank=False)

    bruderschaft = models.ForeignKey(Bruderschaft, blank=True, null=True)
    domination = models.ForeignKey(Domination, blank=True, null=True)
    contact_name = models.CharField(max_length=250, blank=True)
    contact_phone = models.CharField(max_length=15, blank=False)
    contact_e_mail = models.EmailField(max_length=256, blank=True)
    contact_website = models.URLField(max_length=500, blank=True)

    position = models.PointField(srid=4326)
    objects = models.GeoManager

    added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'{obj.name}: {obj.street} {obj.hous_number} {obj.postcode} {obj.city} ({obj.position.x}, {obj.position.y})'.format(
            obj=self)


class ReccuringEvent(models.Model):
    name = models.CharField(max_length=250, blank=False)
    description = models.TextField(blank=False)

    day_of_week = custom_fields.DayOfTheWeekField(blank=False)
    time = models.TimeField(blank=False)
    duration = models.DurationField(blank=True)

    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    def __unicode__(self):
        return u'{obj.name} {obj.description}'.format(obj=self)


class SingleEvent(models.Model):
    name = models.CharField(max_length=250, blank=False)
    description = models.TextField(blank=False)

    date = models.DateField(blank=False)
    time = models.TimeField(blank=False)
    duration = models.DurationField(blank=True)

    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    def __unicode__(self):
        return u'{obj.name} {obj.description}'.format(obj=self)

bibeltreue-gemeinden/app/forms.py
"""
Definition of forms.
"""

from django.contrib.gis import forms
from django.contrib.auth.models import User
from app.models import Profile, Place, Domination, Bruderschaft
from app.custom_fields import CharPointField
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import ugettext_lazy as _


class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': _('User name')}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder': _('Password')}))


class BootstrapSignUpForm(UserCreationForm):
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': _('User name')}))
    email = forms.EmailField(max_length=254, help_text=_('Required. Inform a valid email address.'),
                             widget=forms.TextInput({
                                 'class': 'form-control',
                                 'placeholder': _('E-Mail')}))

    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput({
                                    'class': 'form-control',
                                    'placeholder': _('Password')}))

    password2 = forms.CharField(label=_("Retype Password"),
                                widget=forms.PasswordInput({
                                    'class': 'form-control',
                                    'placeholder': _('Retype Password')}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=254,
                                 widget=forms.TextInput({
                                     'class': 'form-control',
                                     'placeholder': _('First Name')}))
    last_name = forms.CharField(max_length=254,
                                widget=forms.TextInput({
                                    'class': 'form-control',
                                    'placeholder': _('Last Name')}))

    email = forms.EmailField(max_length=254,
                             widget=forms.TextInput({
                                 'class': 'form-control',
                                 'placeholder': _('E-Mail')}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)


class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea({
        'class': 'form-control',
        'title': _('Describe yourself'),
        'placeholder': _('Describe yourself')}), required=False)

    class Meta:
        model = Profile
        fields = ('bio',)


class PlaceForm(forms.ModelForm):
    name = forms.CharField(max_length=254,
                           widget=forms.TextInput({
                               'class': 'form-control',
                               'placeholder': _('Name')}))

    description = forms.CharField(widget=forms.Textarea({
        'class': 'form-control',
        'title': _('Describe this Place'),
        'placeholder': _('description')}), required=False)

    street = forms.CharField(min_length=4, max_length=254,
                             widget=forms.TextInput({
                                 'class': 'form-control',
                                 'placeholder': _('Street')}))

    hous_number = forms.CharField(max_length=254,
                                  widget=forms.TextInput({
                                      'class': 'form-control',
                                      'placeholder': _('Hous Number')}))

    postcode = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': _('Postcode')}))

    city = forms.CharField(max_length=254,
                           widget=forms.TextInput({
                               'class': 'form-control',
                               'placeholder': _('City')}))

    country = forms.CharField(max_length=254, initial='Deutschland',
                              widget=forms.TextInput({
                                  'class': 'form-control',
                                  'placeholder': _('Country')}))
    contact_name = forms.CharField(max_length=254,
                                   widget=forms.TextInput({
                                       'class': 'form-control',
                                       'placeholder': _('First and family name')}), required=False)
    contact_phone = forms.CharField(max_length=254,
                                    widget=forms.TextInput({
                                        'class': 'form-control',
                                        'placeholder': _('Phone')}), required=False)
    contact_e_mail = forms.EmailField(max_length=254,
                                      widget=forms.TextInput({
                                          'class': 'form-control',
                                          'placeholder': _('E-Mail')}), required=False)

    contact_website = forms.URLField(max_length=254,
                                     widget=forms.TextInput({
                                         'class': 'form-control',
                                         'placeholder': _('Website')}), required=False)

    bruderschaft = forms.ModelChoiceField(queryset=Bruderschaft.objects.all(), required=False)

    domination = forms.ModelChoiceField(queryset=Domination.objects.all(), required=False)

    position = CharPointField(widget=forms.TextInput({
        'class': 'form-control',
        'placeholder': _('From map'),
        'readonly': 'readonly',
        'title': _('Use map to set'), }))

    class Meta:
        model = Place
        fields = (
        'name', 'street', 'hous_number', 'postcode', 'city', 'country', 'description', 'contact_name', 'contact_phone',
        'contact_e_mail', 'contact_website', 'position', 'bruderschaft', 'domination')

bibeltreue-gemeinden/app/templates/app/about.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}

<h2>{% trans "About"%}</h2>
<h3>{% trans "Why this site"%}</h3>
<p>{% blocktrans %}This site has been created to help christians to find a place of worship when they are in a new place. {% endblocktrans %}
</p>
<h3>{% trans "Which churches"%}</h3>
<p>{% blocktrans %}All Churches on this Site are added if they meet this set of criteria. {% endblocktrans %}
</p>
<h3>{% trans "I want to participate"%}</h3>
<p>{% blocktrans %}They are several ways how you can participate and help other people to find the next chruch.  {% endblocktrans %}
</p>

{% endblock %}

bibeltreue-gemeinden/app/templates/app/account_activation_email.html
{% load i18n %}
{% autoescape off %}
{% trans "Hello"%} {{ user.username }},

{% trans "Please click on the link below to confirm your registration:"%}

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

bibeltreue-gemeinden/app/templates/app/account_activation_invalid.html
{% load i18n %}
{% extends "app/layout.html" %}

{% block content %}
  <p>{% trans "The confirmation link was invalid, possibly because it has already been used."%} </p>
{% endblock %}

bibeltreue-gemeinden/app/templates/app/add_place.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{{ title }}</h2>
    <!--<div class="col-md-12">-->
    <h4>{% trans "Create new Place."%}</h4>
    <hr/>

    <form method="post" class="form-vertical">
        <section id="newPlaces" class="col-md-5">

            {% csrf_token %}

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} fade in">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <table>
                {{ place_form.as_table }}
            </table>
            <br>
            <input type="submit" value="{% trans "Submit" %}" class="btn btn-default pull-right"/>
        </section>
    </form>
    <div id="addmap">

        <script>
            var map = L.map('addmap')
            map.fitBounds([[55.05, 8.4],[47.270108, 10.178319],[51.05, 5.866667],[51.266667, 15.033333]]);
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 18,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map);
            marker = null

            function onMapClick(e) {
                if (marker == null) {
                    marker = new L.marker(e.latlng, {
                        draggable: 'true'
                    });
                }

                marker.on('dragend', function(event) {
                    var marker = event.target;
                    var position = marker.getLatLng();
                    $("#id_position").val(position.lng+","+position.lat);

                    marker.setLatLng(new L.LatLng(position.lat, position.lng), {
                        draggable: 'true'
                    });
                    map.panTo(new L.LatLng(position.lat, position.lng));
                });
                map.addLayer(marker);
                var position = marker.getLatLng();
                $("#id_position").val(position.lng+","+position.lat);
            };

            map.on('click', onMapClick);
        </script>

    </div>

    <!--</div>-->

</div>

{% endblock %}

bibeltreue-gemeinden/app/templates/app/edit_place.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{{ title }}</h2>
    <h4>{% trans "Edit Place." %}</h4>
    <hr/>
    <form method="post" class="form-horizontal">
        <section id="newPlaces" class="col-md-4">
            {% csrf_token %}

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} fade in">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <table>
                {{ place_form.as_table }}
            </table>
            <br>
            <input type="submit" value="{% trans " Submit" %}" class="btn btn-default pull-right"/>
        </section>

    </form>
    <div div id="addmap">

        <script>
        //In django the lat and lon are switched. x =  lon y = lat
        django_position = new L.LatLng({{ place_form.position.value }});
        converted_position = new L.LatLng(django_position.lng, django_position.lat);

        var map = L.map('addmap').setView(converted_position, 10);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);



        function createMarker(marker, initial_position){
            if (marker == null) {
                marker = new L.marker(initial_position, {
                    draggable: 'true'
                });
            }

            marker.on('dragend', function(event) {
                var marker = event.target;
                var position = marker.getLatLng();
                $("#id_position").val(position.lng+","+position.lat);

                marker.setLatLng(new L.LatLng(position.lat, position.lng), {
                    draggable: 'true'
                });
                map.panTo(new L.LatLng(position.lat, position.lng));
            });
            map.addLayer(marker);
            var position = marker.getLatLng();
            $("#id_position").val(position.lng+","+position.lat);

        };


        createMarker(null,converted_position);
        //console.log({{place_form.position}})

        </script>

    </div>
</div>
{% endblock %}

bibeltreue-gemeinden/app/templates/app/index.html
{% extends "app/layout.html" %}
{% load i18n %}
{% block content %}

<div class="container">


    <form class="row" role="search">
        <div class="input-group">

            <input id="search_place" type="text" class="form-control" placeholder="Enter Address">

            <div class="input-group-btn">
                <button type="button" class="btn btn-search btn-default dropdown-toggle"
                        data-toggle="dropdown">
                    <span class="glyphicon glyphicon-search"></span>
                    <span class="label-icon">{% trans "Radius" %}</span>
                    <span class="label-icon radius_number">10</span>
                    <span class="label-icon">km</span>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-left" role="menu">
                    <li>
                        <a href="#">
                            <span class="label-icon radius_number">10</span>
                            <span class="label-icon">km</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="label-icon radius_number">25</span>
                            <span class="label-icon">km</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="label-icon radius_number">50</span>
                            <span class="label-icon">km</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="label-icon radius_number">100</span>
                            <span class="label-icon">km</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="input-group-btn">
                <button type="button" class="btn btn-search btn-default" onclick="searchPlace()">
                    {% trans "Search" %}
                </button>


            </div>
        </div>
    </form>

    <div class="row"></div>

</div>
<div id="mapid">
        <script>

        function get_corner_points_from_map(map){
            var bounds = map.getBounds();
            var northeast = bounds._northEast
            var southwest = bounds._southWest

            var bounding_box = [[northeast.lat, northeast.lat], [southwest.lng, northeast.lat], [southwest.lng, southwest.lat], [northeast.lng, southwest.lat]]

            return bounding_box
        }

        function get_all_places(map) {
            var bounding_box = get_corner_points_from_map(map)

            //var jsonObject = {"bounding_box":bounding_box}
            var jsonString = JSON.stringify(bounding_box);
            //console.log(bounding_box);
            //console.log(jsonObject);
            //console.log(jsonString);

            $.ajax({
                url: '{% url 'bounding_box' %}',
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                dataType: 'text',
                data: {'bounding_box':jsonString},
                success: function(result) {
                    markersLayer.clearLayers();
                    var jsonObject = $.parseJSON(result);
                    var markers = jsonObject.markers

                    var markerFeatureGroup = L.featureGroup()
                    for (marker of markers) {
                        var loc = new L.LatLng(marker.location.lat, marker.location.lon)
                        console.log(marker.passed_days)
                        if (marker.passed_days < not_new_days) {
                            var mapMarker = new L.marker(loc, {icon: redIcon})
                        } else {
                            var mapMarker = new L.marker(loc, {icon: blueIcon})
                        }
                        mapMarker.bindPopup(marker.popup)
                        markersLayer.addLayer(mapMarker);
                        markerFeatureGroup.addLayer(mapMarker)
                    }
                    mymap.fitBounds(markerFeatureGroup.getBounds());
                }
            });
            markersLayer.addTo(mymap);
        };

        var mymap = L.map('mapid');
        mymap.fitBounds([[55.05, 8.4],[47.270108, 10.178319],[51.05, 5.866667],[51.266667, 15.033333]]);
        var markersLayer = new L.layerGroup();
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(mymap);
        var radius = 10
        $(".input-group-btn .dropdown-menu li a").click(function(){
            var selText = $(this).html();
           $(this).parents('.input-group-btn').find('.btn-search').html('Radius' +selText);
           radius = $(this).find('.radius_number')[0].innerText
        });

        var LeafIcon = L.Icon.extend({
            options: {
                iconSize:     [19, 19],
                iconAnchor:   [19, 19],
                popupAnchor:  [-10, -19]
            }
        });

        {% load static %}
        var blueIcon = new LeafIcon({iconUrl: '{% static '/app/images/church.png' %}'})
        var redIcon = new LeafIcon({iconUrl: '{% static '/app/images/church-red.png' %}'})

        get_all_places(mymap);

        function searchPlace(e) {
            var searchString = $("#search_place").val()
            var jsonObject = new Object()
            jsonObject.query = searchString
            jsonObject.radius = radius
            var jsonString = JSON.stringify(jsonObject)

            $.ajax({
                url: '{% url 'osm_location' %}',
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                data: jsonObject,
                dataType: 'text',
                success: function(result) {
                    markersLayer.clearLayers();
                    var jsonObject = $.parseJSON(result);
                    var center = jsonObject.center;
                    var markers = jsonObject.markers;


                    var markerFeatureGroup = L.featureGroup()
                    for (marker of markers) {
                        var loc = new L.LatLng(marker.location.lat, marker.location.lon)
                        console.log(marker.passed_days)
                        if (marker.passed_days < not_new_days) {
                            var mapMarker = new L.marker(loc, {icon: redIcon})
                        } else {
                            var mapMarker = new L.marker(loc, {icon: blueIcon})
                        }
                        mapMarker.bindPopup(marker.popup)
                        markersLayer.addLayer(mapMarker);
                        markerFeatureGroup.addLayer(mapMarker);
                    }
                    var rad = radius * 1000

                    var circle = L.circle(new L.LatLng(center.lat, center.lon), {
                        color: 'blue',
                        dashArray: "30 10",
                        weight: 0,
                        fillColor: '#009ACD',
                        fillOpacity: 0.2,
                        radius: rad,
                    });
                    markersLayer.addLayer(circle);
                    markerFeatureGroup.addLayer(circle)
                    //mymap.panTo(new L.LatLng(center.lat, center.lon))
                    mymap.fitBounds(markerFeatureGroup.getBounds());
                }
            });

            markersLayer.addTo(mymap);

        };
        </script>

    </div>

{% endblock %}

bibeltreue-gemeinden/app/templates/app/loginpartial.html
{% load i18n %}
{% if user.is_authenticated %}
<form id="logoutForm" action="{% url 'logout' %}" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><a class="navbar-brand" href="{% url 'update_profile' %}">{% trans "Hello"%} {{ user.first_name }}!</a></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">{% trans "Log off"%}</a></li>

    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">{% trans "Log in"%}</a></li>
</ul>

{% endif %}

bibeltreue-gemeinden/app/templates/app/password_reset_form.html
{% extends "app/layout.html" %}
{% load i18n %}

{% load app_filters %}

{% block content %}
<div class="container">
    <div>
        <h2>{% trans "Forgot Password"%}</h2>
        <p>{% trans "Please specify your email address to receive instructions for resetting it."%}</p>
    </div>
    <div>
        <section id="loginForm">
            <form method="post" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email" class="col-xs-1 control-label pull-left">{% trans "E-mail address:"%}</label>
                    <div class="col-sm-9">
                        {{ form.email.errors }}
                        {{ form.email | addcss:"form-control" }}
                    </div>
                    <input type="submit" class="col-sm-2 btn btn-default" value="{% trans "Reset password"%}"/>
                </div>

            </form>
        </section>
    </div>

</div>
{% endblock %}


{% block scripts %}

{% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

bibeltreue-gemeinden/app/templates/app/signup.html
{% extends "app/layout.html" %}
{% load i18n %}

{% block content %}
  <h2>{{ title }}</h2>
<div class="row">
  <div class="col-md-8">
    <section id="signupForm">
        <form method="post" class="form-horizontal">
          {% csrf_token %}
          <h4>{% trans "Fill out all data to create an user account."%}</h4>
          <hr />
            {% if form.errors %}
            <div class="alert alert-danger fade in">
                {{ form.errors.username }}
                {{ form.errors.email }}
                {{ form.errors.password1 }}
                {{ form.errors.password2 }}
            </div>
              {% endif %}
            <div class="form-group">
                <label for="id_username" class="col-md-2 control-label">{% trans "User name"%}</label>
                <div class="col-md-10">
                    {{ form.username }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_email" class="col-md-2 control-label">{% trans "E-Mail"%}</label>
                <div class="col-md-10">
                    {{ form.email }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_password1" class="col-md-2 control-label">{% trans "Password"%}</label>
                <div class="col-md-10">
                    {{ form.password1 }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_password2" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    {{ form.password2 }}
                </div>
            </div>

            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="{% trans "Sign up" %}" class="btn btn-default" />
            </div>
        </form>
    </section>
  </div>

</div>
{% endblock %}